operator:
  tickInterval: 5s
httpRateLimiter:
  maxRequestsInFlightPerHost: 4
  maxRequestsPerSecondPerHost: 20
nsx:
  urlScheme: http
  writesEnabled: true
  auth:
    username: nsx_admin
    password: nsx_password
logging:
  level: debug
