// Code generated by projectlint test. DO NOT EDIT.

package novaluereceivers

type GeneratedController struct{}

func (g GeneratedController) ReconcileGenerated() {} // want "method receiver must be pointer receiver"
