operator:
  tickInterval: 5s
  metricsBindAddress: ":8080"
httpRateLimiter:
  maxRequestsInFlightPerHost: 4
  maxRequestsPerSecondPerHost: 20
kubeAPI:
  numParallelWorkers: 20
  maxRequestsPerSecond: 100
  maxRequestsInFlight: 100
nsx:
  urlScheme: http
  writesEnabled: true
  auth:
    username: nsx_admin
    password: nsx_password
logging:
  level: debug
